version: "3.2"

services:
  rabbit-mq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbit-mq'
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_USER=senhadev
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/lib/rabbitmq/
    networks:
      - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge
